### ISSUE TITLE
Installation fails for Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by chrishowejones** [rvm/ubuntu_rvm#39] opened 2019-07-21 11:49 UTC
## Description

During install exactly following the instructions in this repo I got this message:

```
Creating local gemsets for chris
-su: rvm: command not found
dpkg: error processing package rvm (--configure):
 installed rvm package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 rvm
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I have tried this install in BASH shell and ZSH with the exact same result. I've uninstalled and purged rvm and retried several times with the same result. I have gone through my PATH and the results of 'env' and removed or unset everything referencing RVM. I have logged out and restarted several times after cleaning everything and I still get the same result

## Steps to reproduce

 1. Ran `sudo apt-get install software-properties-common`
 2. Ran `sudo apt-add-repository -y ppa:rael-gc/rvm`
 3. Ran `sudo apt-get update`
 4. Ran `sudo apt-get install rvm`

## Expected behavior

Expected to see a clean install without error messages.

## Actual behavior

* [All commands](https://gist.github.com/chrishowejones/29f9a8306f0ce3c3aa4fb7a610d70195)

## Environment info

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

**Comment by SuperSandro2000** [comment] 2019-07-21 21:58
Same happening on 19.04 Ubuntu.

**Comment by jmarrec** [comment] 2019-07-22 10:18
Duplicate of #37

**Closed** 2019-07-22 19:34 UTC
Labels: duplicate
